### PR TITLE
Changed a few things in BTree implementation

### PR DESCRIPTION
**Pull request by devenbansod**
Changed a few things in BTree implementation

Fixed the findInNode methods.

### CODE REVIEW

**Comment by devenbansod** [comment]
@ajinkya-k : Look at these changes.

**Comment by ajinkya-k** [comment]
Why make `findInNode()` a routine instead of function?

**Comment by devenbansod** [comment]
you only told me it is bad to return structs from functions.

**Comment by ajinkya-k** [comment]
Yeah but we can make it return reference to a struct on heap

**Comment by devenbansod** [comment]
But now, by doing this, we don't even need to go to heap. Am I correct ?

**Comment by rajathshashidhara** [comment]
@ajinkya-k if you allocate memory on heap, who will deallocate it ?
if you expect the user to deallocate it, it is bad design. Because, user should only deallocate the memory he has explicitly allocated.

**Comment by devenbansod** [comment]
Updated the PR. @ajinkya-k : good to merge ?

**Comment by devenbansod** [comment]
Merging!

**Pull request merged**
