### PR TITLE
Took bufferframe, writer and reader outside bufferedfile

### PR DESCRIPTION
**Pull request by mbiswal94**
Signed-off-by: Mihir Biswal mbiswal94@gmail.com

### CODE REVIEW

**Comment by devenbansod** [comment]
@mbiswal94 : does this mean now that I can use `BufferedWriter::memcpy()` like this ? Or do I still need `BufferedFile::BufferedWriter::memcpy` ?

**Comment by mbiswal94** [comment]
yes u can now use BufferedframeWriter::memcpy() on bufferedframe instances.

**Comment by devenbansod** [comment]
Oh. Okay.
So, then this seems fit to merge ?

**Comment by mbiswal94** [comment]
yes. any doubt on dat?! :D

**Comment by devenbansod** [comment]
Nope! :) Who can doubt you @mbiswal94 :P

Merging!

**Comment by devenbansod** [comment]
Just a doubt @mbiswal94 , does this require a change in vector_simple.h ?
Basically I think Rajath wanted to shorten this type of long code https://github.com/ExternalMemoryDS/external-mem-ds/blob/master/src/vector_simple.h#L30

Does this PR help this cause ?

**Pull request merged**
