### PR TITLE
Changes to delete algorithm

### PR DESCRIPTION
**Pull request by ajinkya-k**

### CODE REVIEW

**Comment by ajinkya-k** [comment]
Suggestion:
1. squash only first three commits
2. Keep last 2 commits separate

**Comment by devenbansod** [comment]
Okay. Is it ready ?

**Comment by ajinkya-k** [comment]
No a few things are left

**Comment by ajinkya-k** [comment]
You can merge it with `btree` but not with `master`

**Comment by devenbansod** [comment]
Continue on this till 11.30. I will start reviewing and merge to `btree` after that.

**Comment by devenbansod** [comment]
Merging for now. Will make some changes that I can clearly see. 
You can send in another pull for changes introduced later than this.

**Pull request merged**
